// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/studio/db pull). The Prisma Client at runtime
    // (src/lib/prisma.ts) connects with the pooled DATABASE_URL instead —
    // @prisma/config 7.9.1 has no working `directUrl` option, and running
    // migrations through Supabase's pgbouncer pooler hangs on the advisory
    // lock, so the CLI needs the direct/session connection here.
    url: env("DIRECT_URL"),
  },
});
